apiVersion: v1
kind: Service
metadata:
  labels:
    app: shreesh
  name: 17shreesh
spec:
  type: NodePort
  ports:
    - port: 90
      targetPort: 90
      protocol: TCP
  selector:
    app: shreesh
